name: NarwhalTowns
version: ${project.version}
main: narwhal.narwhaltowns.NarwhalTowns
api-version: 1.19
authors: [ TheNarwhal, Lfwer250 ]
description: Town plugin
commands:
  Town:
    aliases: [t,narwhaltown]
  Money:
  Bank: